---
title: "História da América Independente"
subtitle: "CCLHM0081 - 2024.1"
author: "Eric Brasil"
email: profericbrasil@unilab.edu.br
institute: "Licenciatura em História, IHLM-UNILAB"
date: 08/06/2024
description: "Plano de Ensino da disciplina História da América Independente, ministrada pelo Prof. Eric Brasil, no semestre 2024.1, no curso de Licenciatura em História da UNILAB. Contato: profericbrasil@unilab.edu.br"
lang: pt-BR
logo: logo.png
---

| Código   | Disciplina                       | CH  | Dia | Horário | Sala |
|:--------:|:--------------------------------:|:---:|:---:|:-------:|:----:|
| CCLHM0081| História da América Independente | 60h | 4ª  | 8h-12h  | 5    |

# Ementa

A crise do sistema colonial; Processos de independência e formação dos Estados Nacionais: história e historiografia; A revolução haitiana; Resistência negra, abolicionismos e luta pela cidadania; Povo e revolução na América Central e no Caribe; Populismo, autoritarismo e democracia no século XX; A construção do conceito de “América Latina”. O ensino de história e historiografia da América Latina na escola básica.

---

# Conteúdo Programático

## AULA 1 (07/08/2024): Quem escreve a história das Américas? E que disciplina é essa?

**Bibliografia Básica**

- Graeber, D.; Wengrow D. Liberdade perversa: a crítica indígena e o mito do progresso. In: **O Despertar de tudo**: uma nova história da humanidade. São Paulo: Companhia das Letras, 2022. [Trechos selecionados]

---

# Módulo I - Crise do Sistema colonial e os processos de independência nas Américas<br>

## AULA 2 (14/08/2024): Atividade Remota: Como a inteligência artificial entende nossa disciplina?

- Atividade remota a ser divulgada em breve.<br>

## AULA 3 (21/08/2024): Revolução Americana e a Formação da República dos EUA

**Bibliografia Básica**

- Wood Gordon. "III. Revolução". In: **A revolução americana**. Rio de Janeiro: Objetiva, 2013.
- Viana, Larissa Moreira. “A América negra em tempo de revolução: Raça e republica nos Estados Unidos (1776-1860)”. Revista de História Comparada 8, nº 2 (2014): 146–65.

**Bibliografia Complementar**

- Karnal; Purdy; Fernandes; Morais. "O Início". In: **História dos Estados Unidos: das origens aos século XXI.** São Paulo: Contexto, 2007. pp. 39-80.
- Lemisch, Jesse. “La revolución americana vista desde el fondo”. *Ensayos inconformistas sobre los Estados Unidos*. Barcelona: Peninsula, 1976.
- Linebaugh, Peter, e Marcus Rediker. "A horda heterogênea na Revolução America". In: **A hidra de muitas cabeças: marinheiros, escravos, plebeus e a história oculta do Atlântico revolucionário.** São Paulo: Editora Companhia das Letras, 2008.<br>

## AULA 4 (28/08/2024): A Revolução de Santo Domingo e a Independência do Haiti

**Bibliografia Básica**

- Soares, Ana Loryn, e Elton Batista da Silva. “A revolução do Haiti: um estudo de caso (1791-1804).” Ameríndia - História, cultura e outros combates. 1, nº 1 (1º de setembro de 2006): 08–08.
- James, Cyril Lionel Robert. Os jacobinos negros: Toussaint L’Ouverture e a Revolução de São Domingos. São Paulo: Boitempo, 2000. [Trechos selecionados]

**Bibliografia Complementar**

- Scott, Rebecca J., e Jean M. Hébrard. “‘Rosalie... Minha Escrava’”. Translating the Americas 3, nº 20190612 (julho de 2015).
- Morel, Marco. A Revolução do Haiti e o Brasil escravista. São Paulo: Paco Editorial, 2018.<br>

## AULA 5 (04/08/2024): A construção da nação Haitiana e seus impactos no mundo moderno (1791-1850)

**Bibliografia Básica**

- Vieira, Jofre Teófilo, e Victor Fialho de Assunção. “A crise no Haiti pós-independência, de 1804 – 1915.” Ameríndia - História, cultura e outros combates. 2, nº 1 (1º de janeiro de 2007): 09–09.
- FICK, Carolyn. Para uma (re)definição de liberdade: a Revolução no Haiti e os paradigmas de Liberdade e Igualdade. *Estudos Afro-Asiáticos*, v.26, n.2, Mai-Agosto, 2004.

**Bibliografia Complementar**

- Grafenstein, Johanna von. “Haití En El Siglo XIX. Desde La Revolución de Esclavos Hasta La Ocupación Norteamericana (1791-1915)” Istor, Revista de Historia Internacional, CIDE, Año XII, Número 46. Otoño de 2011, Pp. 3- 32.<br>

## AULA 6 (11/09/2024): Independências da América Hispânica

**Bibliografia básica**

- Mäder, Maria Elisa Noronha de Sá. Revoluções de independência na América Hispânica: uma reflexão historiográfica. Revista de História, 159, 2008. pp. 225-241.
- Prado, Maria Lígia Coelho, e Gabriela Pellegrino. "Campanhas de independência nos vice-reinos espanóis", "O horizonte republicano nos Estados nacionais em formação". In História da América Latina. 1º ed. São Paulo: Contexto, 2014.<br>

**Bibliografia Complementar**

- Lynch, John. “As origens da independência da América Espanhola”. In História da América Latina: da independência a 1870, Vol. 3. São Paulo: Editora da Universidade de São Paulo, 2004.
- Prado, Maria Lígia Coelho. “A participação das mulheres nas lutas pela independência política da América Latina”. In América Latina no Século XIX: Tramas, Telas e Textos. São Paulo: Edusp, 2ª. São Paulo: Edusp, 2014.<br>

## AULA 7 (18/09/2024): Formação dos Estados Nacionais da América Latina

**Bibliografia Básica**

- Prado, Maria Lígia Coelho. “Sonhos e desilusões nas independências hispano-americanas”. In América Latina no Século XIX: Tramas, Telas e Textos. São Paulo: Edusp, 2ª. São Paulo: Edusp, 2014.
- Wasserman, Claudia. A formação do Estado Nacional na América Latina: as emancipações políticas e o intrincado ordenamento dos novos países. In: **História da América Latina**: cinco séculos (temas e
problemas). 3. ed. Porto Alegre: Editora da UFRGS. p. 177-214.

**Bibliografia Complementar**

- EM BREVE<br>

---

# Módulo II - Abolições, Pós-abolição e Cidadania<br>

## AULA 8 (25/09/2024): Era das Abolições I: Caribe inglês e francês 

**Bibliografia Básica**

- Brasil, Eric. Abolição e Carnaval: performance e experiência social negra em Trinidad (cc. 1790-1850). Revista de Estudos e Pesquisas sobre as Américas 12, nº 3 (2018): 204–27. 
- Canelas, Letícia Gregório. Alforria, direito e política colonial (1830-1848). In: Escravidão e Liberdade no Caribe Francês: a alforria na Martinica sob uma perspectiva de gênero, raça e classe (1830-1848). Doutorado, Unicamp, 2017. 

**Bibliografia Complementar**

- Drescher, Seymour. A emancipação britânica. In: Abolição: uma História da Escravidão e do Antiescravismo. Edição: 1. São Paulo: Editora Unesp, 2011. 
- Beckles, Hilary, e Verene A Shepherd. Freedoms Won: Caribbean Emancipations, Ethnicities, and Nationhood. Cambridge: Cambridge University Press, 2008. pp 7-16.<br>

## AULA 9 (02/10/2024): Era das Abolições II: Guerra Civil e Abolição nos EUA (1861-1865)

**Bibliografia Básica**

- DRESCHER, Seymour. Abolição. pp. 451-573
- IZECKSOHN, Vitor. O recrutamento de negros nas tropas da União durante a guerra civil americana. *Afro-Ásia*, v. 0, n. 55, 3 out. 2017.

**Bibliografia Complementar**

- MIRANDA, Clícea Maria. Repercussões da Guerra Civil Americana no debate político sobre a abolição no Brasil, 1861-1888. Anais do VII Encontro Escravidão e Liberdade no Brasil Meridional, p. 13, 2015.
- OAKES, James. “Não existem rebeldes negros”: repensando o legado de E. P. Thompson para a Guerra Civil Americana. Mundos do Trabalho, v. 11, n. 0, p. 1–13, 22 out. 2019.<br>

## AULA 10 (09/10/2024): Era das Abolições III: Cuba - Abolição e Independência (1870-1900)

**Bibliografia Básica**

- SCOTT, Rebecca J. Abolição Gradual e a Dinâmica da Emancipação dos Escravos em Cuba, 1868-86 | Estudos Econômicos (São Paulo). *Estudos Econômicos*, v. 17, n. 3, p. 457–485, 1987.
- MATA, I. M.. Raça e antiescravismo no Caribe espanhol: o ativismo de Antonio Maceo e Ramón Emeterio Betances. *Revista Brasileira de História*, v. 41, n. 86, p. 13–37, jan. 2021.

**Bibliografia Complementar**

- FERRER, Ada. Cuba, 1898: Rethinking Race, Nation, and Empire. *Radical History Review*, v. 1999, n. 73, p. 22–46, 1999.
- HELG, Aline. Sentido e impacto de la participación negra en la guerra de independencia de Cuba. *Revista de Indias*, v. 58, n. 212, p. 47–63, 1998.<br>

## AULA 11 (16/10/2024): Atividade Remota

Descrição em breve.<br>

## AULA 12 (23/10/2024): Atividade Remota

Descrição em breve.<br>


---

# Módulo III - Revoluções, Estado e Democracia no Século XX<br>


## AULA 13 (30/10/2024): Revolução Mexicana de 1910

**Bibliografia Básica**

- BRUIT, Hector. Revoluções na América Latina. São Paulo: Atual, 1988. "Introdução" e "1. A Revolução Mexicana"

**Bibliografia Complementar**

- Aguilar Camín, Héctor & Meyer, Lorenzo. **À Sombra da Revolução Mexicana**: História mexicana contemporãnea, 1910-1989. São Paulo: EdUSP, 2000. [Trechos selecionados]<br>


## AULA 14 (06/11/2024): Populismo, autoritarismo e democracia no século XX

**Bibliografia Básica**

- EM BREVE

**Bibliografia Complementar**

- EM BREVE<br>


## AULA 15 (13/11/2024): Revolução Cubana de 1959

**Bibliografia Básica**

- MAIA, Iacy Maia e DURÃES, Bruno José R. Cuba, os afro-cubanos e a revolução: passado e presente. História Social, n. 17, segundo semestre de 2009.
- WASSERMAN, Cláudia. Historiografia sobre a Revolução Cubana no Brasil. HISTORIA CARIBE, n. 12, P.P. 57 - 76, 2007

**Bibliografia Complementar**

-SADDI, Rafael; MELO, Érica Isabel. Gênero e Revolução Cubana: reflexões sobre as relações de gênero no Exército Rebelde. Diálogos, vol. 6, núm. 3, sep-dez, 2012, pp. 1267-1287.<br>


## AULA 16 (20/11/2024): Movimentos sociais, direitos civis e direitos humanos no século XX 

**Bibliografia Básica**

- EM BREVE

**Bibliografia Complementar**

- EM BREVE
