project:
  type: website
  output-dir: ../../_site/cclhm0081/aulas
  resources:
    - imgs/

format:
  revealjs:
    theme: white
    slide-number: true
    incremental: false
    preview-links: auto
    chalkboard:
      buttons: true
    logo: ../imgs/banner_logos_hist.png
    footer: |
      <a href="https://ericbrasil.com.br/cclhm0081">CCLHM0081 História da América Independente</a> |
      <a href="https://ericbrasil.com.br/contact/">Contato</a>
